dist: focal

langauge: cpp

os:
    - linux

compiler:
    - gcc

install:
    - sudo apt update
    - sudo apt install build-essential
    - sudo apt install libgtest-dev
    - sudo apt-get install cmake
    - sudo apt-get install -y valgrind
    - sudo apt-get install -y gcovr
    - sudo apt install lcov


script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - valgrind --leak-check=yes --error-exitcode=33 -s ./server_test
    - gcovr -r .. --html --html-details -o coverage.html
    